# Generated by Django 3.2.3 on 2021-08-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-updated']},
        ),
    ]
